
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MAGNET_H
#define MAGNET_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 MagNet_valueRangeTest (UNS8 typeValue, void * value);
const indextable * MagNet_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data MagNet_Data;
extern UNS32 MagSwitch;		/* Mapped at index 0x2000, subindex 0x00*/
extern INTEGER16 MagSensorData_CO_MagSensorData_1;		/* Mapped at index 0x2001, subindex 0x01 */
extern INTEGER16 MagSensorData_CO_MagSensorData_2;		/* Mapped at index 0x2001, subindex 0x02 */
extern INTEGER16 MagSensorData_CO_MagSensorData_3;		/* Mapped at index 0x2001, subindex 0x03 */
extern INTEGER16 MagSensorData_CO_MagSensorData_4;		/* Mapped at index 0x2001, subindex 0x04 */
extern INTEGER16 MagSensorData_CO_MagSensorData_5;		/* Mapped at index 0x2001, subindex 0x05 */
extern INTEGER16 MagSensorData_CO_MagSensorData_6;		/* Mapped at index 0x2001, subindex 0x06 */
extern INTEGER16 MagSensorData_CO_MagSensorData_7;		/* Mapped at index 0x2001, subindex 0x07 */
extern INTEGER16 MagSensorData_CO_MagSensorData_8;		/* Mapped at index 0x2001, subindex 0x08 */
extern INTEGER16 MagSensorData_CO_MagSensorData_9;		/* Mapped at index 0x2001, subindex 0x09 */
extern INTEGER16 MagSensorData_CO_MagSensorData_10;		/* Mapped at index 0x2001, subindex 0x0A */
extern INTEGER16 MagSensorData_CO_MagSensorData_11;		/* Mapped at index 0x2001, subindex 0x0B */
extern INTEGER16 MagSensorData_CO_MagSensorData_12;		/* Mapped at index 0x2001, subindex 0x0C */
extern INTEGER16 MagSensorData_CO_MagSensorData_13;		/* Mapped at index 0x2001, subindex 0x0D */
extern INTEGER16 MagSensorData_CO_MagSensorData_14;		/* Mapped at index 0x2001, subindex 0x0E */
extern INTEGER16 MagSensorData_CO_MagSensorData_15;		/* Mapped at index 0x2001, subindex 0x0F */
extern INTEGER16 MagSensorData_CO_MagSensorData_16;		/* Mapped at index 0x2001, subindex 0x10 */
extern INTEGER16 MagSensorData_CO_MagSensorData_17;		/* Mapped at index 0x2001, subindex 0x11 */
extern INTEGER16 MagSensorData_CO_MagSensorData_18;		/* Mapped at index 0x2001, subindex 0x12 */
extern UNS8 FaultStatus;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS8 MagPoisStatus;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS8 ForkSelect;		/* Mapped at index 0x2004, subindex 0x00*/
extern INTEGER16 SelectPoistion;		/* Mapped at index 0x2005, subindex 0x00*/
extern INTEGER16 SelectStrength;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS16 SelectPointNum;		/* Mapped at index 0x2007, subindex 0x00*/
extern INTEGER16 LeftPoistion;		/* Mapped at index 0x2008, subindex 0x00*/
extern INTEGER16 MiddPosition;		/* Mapped at index 0x2009, subindex 0x00*/
extern INTEGER16 RightPosition;		/* Mapped at index 0x200A, subindex 0x00*/
extern INTEGER16 LeftStrength;		/* Mapped at index 0x200B, subindex 0x00*/
extern INTEGER16 MiddStrength;		/* Mapped at index 0x200C, subindex 0x00*/
extern INTEGER16 RightStrength;		/* Mapped at index 0x200D, subindex 0x00*/
extern UNS16 LeftPointNum;		/* Mapped at index 0x200E, subindex 0x00*/
extern UNS16 MiddPointNum;		/* Mapped at index 0x200F, subindex 0x00*/
extern UNS16 RightPointNum;		/* Mapped at index 0x2010, subindex 0x00*/
extern UNS16 SensorPolarity;		/* Mapped at index 0x2011, subindex 0x00*/
extern UNS16 MinPointNumber;		/* Mapped at index 0x2012, subindex 0x00*/
extern UNS16 MaxPointNumber;		/* Mapped at index 0x2013, subindex 0x00*/
extern UNS16 PointDifference;		/* Mapped at index 0x2014, subindex 0x00*/
extern UNS16 SensorSensitivity;		/* Mapped at index 0x2015, subindex 0x00*/
extern UNS16 MiddCenterPostion;		/* Mapped at index 0x2016, subindex 0x00*/
extern UNS16 CanIDAddress;		/* Mapped at index 0x2017, subindex 0x00*/
extern UNS16 CanBaudRate;		/* Mapped at index 0x2018, subindex 0x00*/
extern UNS16 WriteCommand;		/* Mapped at index 0x2019, subindex 0x00*/
extern UNS16 RebootSensor;		/* Mapped at index 0x201A, subindex 0x00*/

#endif // MAGNET_H
