
/* File generated by gen_cfile.py. Should not be modified. */

#include "MagNet.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS32 MagSwitch = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
INTEGER16 MagSensorData_CO_MagSensorData_1 = 0x0;		/* Mapped at index 0x2001, subindex 0x01 */
INTEGER16 MagSensorData_CO_MagSensorData_2 = 0x0;		/* Mapped at index 0x2001, subindex 0x02 */
INTEGER16 MagSensorData_CO_MagSensorData_3 = 0x0;		/* Mapped at index 0x2001, subindex 0x03 */
INTEGER16 MagSensorData_CO_MagSensorData_4 = 0x0;		/* Mapped at index 0x2001, subindex 0x04 */
INTEGER16 MagSensorData_CO_MagSensorData_5 = 0x0;		/* Mapped at index 0x2001, subindex 0x05 */
INTEGER16 MagSensorData_CO_MagSensorData_6 = 0x0;		/* Mapped at index 0x2001, subindex 0x06 */
INTEGER16 MagSensorData_CO_MagSensorData_7 = 0x0;		/* Mapped at index 0x2001, subindex 0x07 */
INTEGER16 MagSensorData_CO_MagSensorData_8 = 0x0;		/* Mapped at index 0x2001, subindex 0x08 */
INTEGER16 MagSensorData_CO_MagSensorData_9 = 0x0;		/* Mapped at index 0x2001, subindex 0x09 */
INTEGER16 MagSensorData_CO_MagSensorData_10 = 0x0;		/* Mapped at index 0x2001, subindex 0x0A */
INTEGER16 MagSensorData_CO_MagSensorData_11 = 0x0;		/* Mapped at index 0x2001, subindex 0x0B */
INTEGER16 MagSensorData_CO_MagSensorData_12 = 0x0;		/* Mapped at index 0x2001, subindex 0x0C */
INTEGER16 MagSensorData_CO_MagSensorData_13 = 0x0;		/* Mapped at index 0x2001, subindex 0x0D */
INTEGER16 MagSensorData_CO_MagSensorData_14 = 0x0;		/* Mapped at index 0x2001, subindex 0x0E */
INTEGER16 MagSensorData_CO_MagSensorData_15 = 0x0;		/* Mapped at index 0x2001, subindex 0x0F */
INTEGER16 MagSensorData_CO_MagSensorData_16 = 0x0;		/* Mapped at index 0x2001, subindex 0x10 */
INTEGER16 MagSensorData_CO_MagSensorData_17 = 0x0;		/* Mapped at index 0x2001, subindex 0x11 */
INTEGER16 MagSensorData_CO_MagSensorData_18 = 0x0;		/* Mapped at index 0x2001, subindex 0x12 */
UNS8 FaultStatus = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS8 MagPoisStatus = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS8 ForkSelect = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
INTEGER16 SelectPoistion = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
INTEGER16 SelectStrength = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
UNS16 SelectPointNum = 0x0;		/* Mapped at index 0x2007, subindex 0x00 */
INTEGER16 LeftPoistion = 0x0;		/* Mapped at index 0x2008, subindex 0x00 */
INTEGER16 MiddPosition = 0x0;		/* Mapped at index 0x2009, subindex 0x00 */
INTEGER16 RightPosition = 0x0;		/* Mapped at index 0x200A, subindex 0x00 */
INTEGER16 LeftStrength = 0x0;		/* Mapped at index 0x200B, subindex 0x00 */
INTEGER16 MiddStrength = 0x0;		/* Mapped at index 0x200C, subindex 0x00 */
INTEGER16 RightStrength = 0x0;		/* Mapped at index 0x200D, subindex 0x00 */
UNS16 LeftPointNum = 0x0;		/* Mapped at index 0x200E, subindex 0x00 */
UNS16 MiddPointNum = 0x0;		/* Mapped at index 0x200F, subindex 0x00 */
UNS16 RightPointNum = 0x0;		/* Mapped at index 0x2010, subindex 0x00 */
UNS16 SensorPolarity = 0x0;		/* Mapped at index 0x2011, subindex 0x00 */
UNS16 MinPointNumber = 0x0;		/* Mapped at index 0x2012, subindex 0x00 */
UNS16 MaxPointNumber = 0x0;		/* Mapped at index 0x2013, subindex 0x00 */
UNS16 PointDifference = 0x0;		/* Mapped at index 0x2014, subindex 0x00 */
UNS16 SensorSensitivity = 0x0;		/* Mapped at index 0x2015, subindex 0x00 */
UNS16 MiddCenterPostion = 0x0;		/* Mapped at index 0x2016, subindex 0x00 */
UNS16 CanIDAddress = 0x0;		/* Mapped at index 0x2017, subindex 0x00 */
UNS16 CanBaudRate = 0x0;		/* Mapped at index 0x2018, subindex 0x00 */
UNS16 WriteCommand = 0x0;		/* Mapped at index 0x2019, subindex 0x00 */
UNS16 RebootSensor = 0x0;		/* Mapped at index 0x201A, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 MagNet_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 MagNet_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 MagNet_iam_a_slave = 1;

TIMER_HANDLE MagNet_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 MagNet_obj1000 = 0x5014;	/* 20500 */
                    subindex MagNet_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&MagNet_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 MagNet_obj1001 = 0x0;	/* 0 */
                    subindex MagNet_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MagNet_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 MagNet_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 MagNet_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex MagNet_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&MagNet_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MagNet_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 MagNet_obj1005 = 0x0;	/* 0 */
                    subindex MagNet_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1005, NULL }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 MagNet_obj1006 = 0x0;	/* 0 */
                    subindex MagNet_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1006, NULL }
                     };

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 MagNet_obj1008[15] = "Hinson MGS-160N";
                    subindex MagNet_Index1008[] = 
                     {
                       { RO, visible_string, 15, (void*)&MagNet_obj1008, NULL }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 MagNet_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 MagNet_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 MagNet_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 MagNet_highestSubIndex_obj1016 = 0;
                    UNS32 MagNet_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 MagNet_obj1017 = 0;	/* 0 */
                    subindex MagNet_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&MagNet_obj1017, NULL }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 MagNet_highestSubIndex_obj1018 = 3; /* number of subindex - 1*/
                    UNS32 MagNet_obj1018_Vendor_ID = 0x1;	/* 1 */
                    UNS32 MagNet_obj1018_Product_Code = 0x1;	/* 1 */
                    UNS32 MagNet_obj1018_Revision_Number = 0x10000;	/* 65536 */
                    subindex MagNet_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MagNet_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MagNet_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MagNet_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MagNet_obj1018_Revision_Number, NULL }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 MagNet_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 MagNet_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 MagNet_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex MagNet_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MagNet_highestSubIndex_obj1200, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MagNet_obj1200_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MagNet_obj1200_COB_ID_Server_to_Client_Transmit_SDO, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 MagNet_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 MagNet_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 MagNet_obj1400_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 MagNet_obj1400_Inhibit_Time = 0x5;	/* 5 */
                    UNS8 MagNet_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MagNet_obj1400_Event_Timer = 0xA;	/* 10 */
                    subindex MagNet_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MagNet_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MagNet_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MagNet_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MagNet_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MagNet_obj1400_Event_Timer, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 MagNet_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 MagNet_obj1600[] = 
                    {
                      0x20040008	/* 537133064 */
                    };
                    subindex MagNet_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MagNet_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1600[0], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 MagNet_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 MagNet_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 MagNet_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 MagNet_obj1800_Inhibit_Time = 0xA;	/* 10 */
                    UNS8 MagNet_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MagNet_obj1800_Event_Timer = 0xA;	/* 10 */
                    subindex MagNet_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MagNet_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MagNet_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MagNet_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MagNet_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MagNet_obj1800_Event_Timer, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 MagNet_highestSubIndex_obj1801 = 5; /* number of subindex - 1*/
                    UNS32 MagNet_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 MagNet_obj1801_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 MagNet_obj1801_Inhibit_Time = 0xA;	/* 10 */
                    UNS8 MagNet_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MagNet_obj1801_Event_Timer = 0xA;	/* 10 */
                    subindex MagNet_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MagNet_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MagNet_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MagNet_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MagNet_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MagNet_obj1801_Event_Timer, NULL }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 MagNet_highestSubIndex_obj1802 = 5; /* number of subindex - 1*/
                    UNS32 MagNet_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 MagNet_obj1802_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 MagNet_obj1802_Inhibit_Time = 0xA;	/* 10 */
                    UNS8 MagNet_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MagNet_obj1802_Event_Timer = 0xA;	/* 10 */
                    subindex MagNet_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MagNet_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MagNet_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MagNet_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MagNet_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MagNet_obj1802_Event_Timer, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 MagNet_highestSubIndex_obj1A00 = 5; /* number of subindex - 1*/
                    UNS32 MagNet_obj1A00[] = 
                    {
                      0x20020008,	/* 537001992 */
                      0x20030008,	/* 537067528 */
                      0x20050010,	/* 537198608 */
                      0x20060010,	/* 537264144 */
                      0x20070010	/* 537329680 */
                    };
                    subindex MagNet_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MagNet_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1A00[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1A00[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1A00[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1A00[4], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 MagNet_highestSubIndex_obj1A01 = 5; /* number of subindex - 1*/
                    UNS32 MagNet_obj1A01[] = 
                    {
                      0x20080010,	/* 537395216 */
                      0x20090010,	/* 537460752 */
                      0x200A0010,	/* 537526288 */
                      0x20090010,	/* 537460752 */
                      0x200A0010	/* 537526288 */
                    };
                    subindex MagNet_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MagNet_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1A01[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1A01[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1A01[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1A01[4], NULL }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 MagNet_highestSubIndex_obj1A02 = 1; /* number of subindex - 1*/
                    UNS32 MagNet_obj1A02[] = 
                    {
                      0x20000020	/* 536870944 */
                    };
                    subindex MagNet_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MagNet_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MagNet_obj1A02[0], NULL }
                     };

/* index 0x2000 :   Mapped variable MagSwitch */
                    subindex MagNet_Index2000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&MagSwitch, NULL }
                     };

/* index 0x2001 :   Mapped variable MagSensorData */
                    UNS8 MagNet_highestSubIndex_obj2001 = 18; /* number of subindex - 1*/
                    subindex MagNet_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MagNet_highestSubIndex_obj2001, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_1, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_2, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_3, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_4, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_5, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_6, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_7, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_8, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_9, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_10, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_11, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_12, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_13, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_14, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_15, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_16, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_17, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MagSensorData_CO_MagSensorData_18, NULL }
                     };

/* index 0x2002 :   Mapped variable FaultStatus */
                    subindex MagNet_Index2002[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&FaultStatus, NULL }
                     };

/* index 0x2003 :   Mapped variable MagPoisStatus */
                    subindex MagNet_Index2003[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MagPoisStatus, NULL }
                     };

/* index 0x2004 :   Mapped variable ForkSelect */
                    subindex MagNet_Index2004[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ForkSelect, NULL }
                     };

/* index 0x2005 :   Mapped variable SelectPoistion */
                    subindex MagNet_Index2005[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&SelectPoistion, NULL }
                     };

/* index 0x2006 :   Mapped variable SelectStrength */
                    subindex MagNet_Index2006[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&SelectStrength, NULL }
                     };

/* index 0x2007 :   Mapped variable SelectPointNum */
                    subindex MagNet_Index2007[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&SelectPointNum, NULL }
                     };

/* index 0x2008 :   Mapped variable LeftPoistion */
                    subindex MagNet_Index2008[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&LeftPoistion, NULL }
                     };

/* index 0x2009 :   Mapped variable MiddPosition */
                    subindex MagNet_Index2009[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&MiddPosition, NULL }
                     };

/* index 0x200A :   Mapped variable RightPosition */
                    subindex MagNet_Index200A[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&RightPosition, NULL }
                     };

/* index 0x200B :   Mapped variable LeftStrength */
                    subindex MagNet_Index200B[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&LeftStrength, NULL }
                     };

/* index 0x200C :   Mapped variable MiddStrength */
                    subindex MagNet_Index200C[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&MiddStrength, NULL }
                     };

/* index 0x200D :   Mapped variable RightStrength */
                    subindex MagNet_Index200D[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&RightStrength, NULL }
                     };

/* index 0x200E :   Mapped variable LeftPointNum */
                    subindex MagNet_Index200E[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&LeftPointNum, NULL }
                     };

/* index 0x200F :   Mapped variable MiddPointNum */
                    subindex MagNet_Index200F[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&MiddPointNum, NULL }
                     };

/* index 0x2010 :   Mapped variable RightPointNum */
                    subindex MagNet_Index2010[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&RightPointNum, NULL }
                     };

/* index 0x2011 :   Mapped variable SensorPolarity */
                    subindex MagNet_Index2011[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SensorPolarity, NULL }
                     };

/* index 0x2012 :   Mapped variable MinPointNumber */
                    subindex MagNet_Index2012[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&MinPointNumber, NULL }
                     };

/* index 0x2013 :   Mapped variable MaxPointNumber */
                    subindex MagNet_Index2013[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&MaxPointNumber, NULL }
                     };

/* index 0x2014 :   Mapped variable PointDifference */
                    subindex MagNet_Index2014[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&PointDifference, NULL }
                     };

/* index 0x2015 :   Mapped variable SensorSensitivity */
                    subindex MagNet_Index2015[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&SensorSensitivity, NULL }
                     };

/* index 0x2016 :   Mapped variable MiddCenterPostion */
                    subindex MagNet_Index2016[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&MiddCenterPostion, NULL }
                     };

/* index 0x2017 :   Mapped variable CanIDAddress */
                    subindex MagNet_Index2017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&CanIDAddress, NULL }
                     };

/* index 0x2018 :   Mapped variable CanBaudRate */
                    subindex MagNet_Index2018[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&CanBaudRate, NULL }
                     };

/* index 0x2019 :   Mapped variable WriteCommand */
                    subindex MagNet_Index2019[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&WriteCommand, NULL }
                     };

/* index 0x201A :   Mapped variable RebootSensor */
                    subindex MagNet_Index201A[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&RebootSensor, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable MagNet_objdict[] = 
{
  { (subindex*)MagNet_Index1000,sizeof(MagNet_Index1000)/sizeof(MagNet_Index1000[0]), 0x1000},
  { (subindex*)MagNet_Index1001,sizeof(MagNet_Index1001)/sizeof(MagNet_Index1001[0]), 0x1001},
  { (subindex*)MagNet_Index1005,sizeof(MagNet_Index1005)/sizeof(MagNet_Index1005[0]), 0x1005},
  { (subindex*)MagNet_Index1006,sizeof(MagNet_Index1006)/sizeof(MagNet_Index1006[0]), 0x1006},
  { (subindex*)MagNet_Index1008,sizeof(MagNet_Index1008)/sizeof(MagNet_Index1008[0]), 0x1008},
  { (subindex*)MagNet_Index1017,sizeof(MagNet_Index1017)/sizeof(MagNet_Index1017[0]), 0x1017},
  { (subindex*)MagNet_Index1018,sizeof(MagNet_Index1018)/sizeof(MagNet_Index1018[0]), 0x1018},
  { (subindex*)MagNet_Index1200,sizeof(MagNet_Index1200)/sizeof(MagNet_Index1200[0]), 0x1200},
  { (subindex*)MagNet_Index1400,sizeof(MagNet_Index1400)/sizeof(MagNet_Index1400[0]), 0x1400},
  { (subindex*)MagNet_Index1600,sizeof(MagNet_Index1600)/sizeof(MagNet_Index1600[0]), 0x1600},
  { (subindex*)MagNet_Index1800,sizeof(MagNet_Index1800)/sizeof(MagNet_Index1800[0]), 0x1800},
  { (subindex*)MagNet_Index1801,sizeof(MagNet_Index1801)/sizeof(MagNet_Index1801[0]), 0x1801},
  { (subindex*)MagNet_Index1802,sizeof(MagNet_Index1802)/sizeof(MagNet_Index1802[0]), 0x1802},
  { (subindex*)MagNet_Index1A00,sizeof(MagNet_Index1A00)/sizeof(MagNet_Index1A00[0]), 0x1A00},
  { (subindex*)MagNet_Index1A01,sizeof(MagNet_Index1A01)/sizeof(MagNet_Index1A01[0]), 0x1A01},
  { (subindex*)MagNet_Index1A02,sizeof(MagNet_Index1A02)/sizeof(MagNet_Index1A02[0]), 0x1A02},
  { (subindex*)MagNet_Index2000,sizeof(MagNet_Index2000)/sizeof(MagNet_Index2000[0]), 0x2000},
  { (subindex*)MagNet_Index2001,sizeof(MagNet_Index2001)/sizeof(MagNet_Index2001[0]), 0x2001},
  { (subindex*)MagNet_Index2002,sizeof(MagNet_Index2002)/sizeof(MagNet_Index2002[0]), 0x2002},
  { (subindex*)MagNet_Index2003,sizeof(MagNet_Index2003)/sizeof(MagNet_Index2003[0]), 0x2003},
  { (subindex*)MagNet_Index2004,sizeof(MagNet_Index2004)/sizeof(MagNet_Index2004[0]), 0x2004},
  { (subindex*)MagNet_Index2005,sizeof(MagNet_Index2005)/sizeof(MagNet_Index2005[0]), 0x2005},
  { (subindex*)MagNet_Index2006,sizeof(MagNet_Index2006)/sizeof(MagNet_Index2006[0]), 0x2006},
  { (subindex*)MagNet_Index2007,sizeof(MagNet_Index2007)/sizeof(MagNet_Index2007[0]), 0x2007},
  { (subindex*)MagNet_Index2008,sizeof(MagNet_Index2008)/sizeof(MagNet_Index2008[0]), 0x2008},
  { (subindex*)MagNet_Index2009,sizeof(MagNet_Index2009)/sizeof(MagNet_Index2009[0]), 0x2009},
  { (subindex*)MagNet_Index200A,sizeof(MagNet_Index200A)/sizeof(MagNet_Index200A[0]), 0x200A},
  { (subindex*)MagNet_Index200B,sizeof(MagNet_Index200B)/sizeof(MagNet_Index200B[0]), 0x200B},
  { (subindex*)MagNet_Index200C,sizeof(MagNet_Index200C)/sizeof(MagNet_Index200C[0]), 0x200C},
  { (subindex*)MagNet_Index200D,sizeof(MagNet_Index200D)/sizeof(MagNet_Index200D[0]), 0x200D},
  { (subindex*)MagNet_Index200E,sizeof(MagNet_Index200E)/sizeof(MagNet_Index200E[0]), 0x200E},
  { (subindex*)MagNet_Index200F,sizeof(MagNet_Index200F)/sizeof(MagNet_Index200F[0]), 0x200F},
  { (subindex*)MagNet_Index2010,sizeof(MagNet_Index2010)/sizeof(MagNet_Index2010[0]), 0x2010},
  { (subindex*)MagNet_Index2011,sizeof(MagNet_Index2011)/sizeof(MagNet_Index2011[0]), 0x2011},
  { (subindex*)MagNet_Index2012,sizeof(MagNet_Index2012)/sizeof(MagNet_Index2012[0]), 0x2012},
  { (subindex*)MagNet_Index2013,sizeof(MagNet_Index2013)/sizeof(MagNet_Index2013[0]), 0x2013},
  { (subindex*)MagNet_Index2014,sizeof(MagNet_Index2014)/sizeof(MagNet_Index2014[0]), 0x2014},
  { (subindex*)MagNet_Index2015,sizeof(MagNet_Index2015)/sizeof(MagNet_Index2015[0]), 0x2015},
  { (subindex*)MagNet_Index2016,sizeof(MagNet_Index2016)/sizeof(MagNet_Index2016[0]), 0x2016},
  { (subindex*)MagNet_Index2017,sizeof(MagNet_Index2017)/sizeof(MagNet_Index2017[0]), 0x2017},
  { (subindex*)MagNet_Index2018,sizeof(MagNet_Index2018)/sizeof(MagNet_Index2018[0]), 0x2018},
  { (subindex*)MagNet_Index2019,sizeof(MagNet_Index2019)/sizeof(MagNet_Index2019[0]), 0x2019},
  { (subindex*)MagNet_Index201A,sizeof(MagNet_Index201A)/sizeof(MagNet_Index201A[0]), 0x201A},
};

const indextable * MagNet_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;break;
		case 0x1006: i = 3;break;
		case 0x1008: i = 4;break;
		case 0x1017: i = 5;break;
		case 0x1018: i = 6;break;
		case 0x1200: i = 7;break;
		case 0x1400: i = 8;break;
		case 0x1600: i = 9;break;
		case 0x1800: i = 10;break;
		case 0x1801: i = 11;break;
		case 0x1802: i = 12;break;
		case 0x1A00: i = 13;break;
		case 0x1A01: i = 14;break;
		case 0x1A02: i = 15;break;
		case 0x2000: i = 16;break;
		case 0x2001: i = 17;break;
		case 0x2002: i = 18;break;
		case 0x2003: i = 19;break;
		case 0x2004: i = 20;break;
		case 0x2005: i = 21;break;
		case 0x2006: i = 22;break;
		case 0x2007: i = 23;break;
		case 0x2008: i = 24;break;
		case 0x2009: i = 25;break;
		case 0x200A: i = 26;break;
		case 0x200B: i = 27;break;
		case 0x200C: i = 28;break;
		case 0x200D: i = 29;break;
		case 0x200E: i = 30;break;
		case 0x200F: i = 31;break;
		case 0x2010: i = 32;break;
		case 0x2011: i = 33;break;
		case 0x2012: i = 34;break;
		case 0x2013: i = 35;break;
		case 0x2014: i = 36;break;
		case 0x2015: i = 37;break;
		case 0x2016: i = 38;break;
		case 0x2017: i = 39;break;
		case 0x2018: i = 40;break;
		case 0x2019: i = 41;break;
		case 0x201A: i = 42;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &MagNet_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status MagNet_PDO_status[3] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index MagNet_firstIndex = {
  7, /* SDO_SVR */
  0, /* SDO_CLT */
  8, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  10, /* PDO_TRS */
  13 /* PDO_TRS_MAP */
};

const quick_index MagNet_lastIndex = {
  7, /* SDO_SVR */
  0, /* SDO_CLT */
  8, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  12, /* PDO_TRS */
  15 /* PDO_TRS_MAP */
};

const UNS16 MagNet_ObjdictSize = sizeof(MagNet_objdict)/sizeof(MagNet_objdict[0]); 

CO_Data MagNet_Data = CANOPEN_NODE_DATA_INITIALIZER(MagNet);

